user: m
pass: 0
host: qa-delivery-mx-master.moneyman.ru
registrationServiceEndpoint: client-area/registration
privateAreaServiceEndpoint: private-area/static/#/login
landingPageServiceEndpoint: /
blackListServiceEndpoint: mxn-crm-gateway/blacklist/contains
signInServiceEndpoint: secure/rest/sign/in
dbUrl: localhost
dbUser: test
dbPassword: testpwd
dbSchema: testdb
crmLogin: 5
crmPass: 6
crmCaptcha: 7
wireMockHost: localhost
wireMockPort: 8084