browserScreenSize: 1920x1080
defaultTimeoutMilliseconds: 100
webDriverHost: 192.168.1.1.
webDriverPort: 5555
browserType: FIREFOX
webDriverType: LOCAL
headlessMode: false
browserStartMaximize: false
browserPageLoadStrategy: normal
