browserScreenSize: 1600x900
defaultTimeoutMilliseconds: 5000
webDriverHost: 192.168.99.100
webDriverPort: 4444
browserType: FIREFOX
webDriverType: REMOTE
headlessMode: false
browserStartMaximize: true
browserPageLoadStrategy: normal
